"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path

# BASE_DIR representa la raíz del proyecto
# Se usa para construir rutas absolutas dentro del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent


# Clave secreta de Django
# En producción debe mantenerse privada
SECRET_KEY = 'django-insecure-v3!74(_a86dd4ayqn&)9lp424+0)o%+@k^med^t!!o8ws!8s46'

# DEBUG activado solo en desarrollo
DEBUG = True

# Hosts permitidos
# En desarrollo puede quedar vacío
ALLOWED_HOSTS = []


# Aplicaciones instaladas en el proyecto
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'finance',           # Nuestra app principal
    'corsheaders',       # Permite configurar CORS para React
]


# Middlewares que procesan cada request/response
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',         # Debe ir primero para CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Archivo principal de rutas del proyecto
ROOT_URLCONF = 'config.urls'


# Configuración del sistema de templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # No usamos templates globales, solo templates por app
        'DIRS': [],

        # Permite a Django buscar templates dentro de cada app
        'APP_DIRS': True,

        'OPTIONS': {
            # Context processors necesarios para autenticación y mensajes
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Punto de entrada WSGI para servidores web
WSGI_APPLICATION = 'config.wsgi.application'


# Configuración de base de datos
# SQLite es suficiente para desarrollo y MVP
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Validadores de contraseñas
# Aumentan la seguridad de los usuarios
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Configuración de idioma
LANGUAGE_CODE = 'en-us'

# Zona horaria
TIME_ZONE = 'UTC'

# Habilita internacionalización
USE_I18N = True

# Usa zonas horarias conscientes
USE_TZ = True


# URL base para archivos estáticos
STATIC_URL = 'static/'


# Tipo de clave primaria por defecto
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Permite que la cookie de sesión se envíe desde el frontend React
# "Lax" permite compartir sesión entre puertos distintos en desarrollo
SESSION_COOKIE_SAMESITE = "Lax"

# En desarrollo debe ser False para permitir HTTP
SESSION_COOKIE_SECURE = False


# Configuración equivalente para la cookie CSRF
# Necesaria para peticiones autenticadas protegidas
CSRF_COOKIE_SAMESITE = "Lax"

# En desarrollo debe ser False
CSRF_COOKIE_SECURE = False


# Configuración de CORS para que React pueda enviar cookies
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",  # Puerto donde corre Vite + React
]


# URL a la que Django redirige después de hacer login
# Evita el error /accounts/profile/
LOGIN_REDIRECT_URL = "/expenses/"

# URL a la que Django redirige después de hacer logout
LOGOUT_REDIRECT_URL = "/accounts/login/"
